name: tree - darwin x86_64

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build --tag test:$(date +%s) dockerfiles/tree/darwin
